services:
  - type: web
    name: jarvis-ia
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-server.txt
    startCommand: gunicorn server:app --workers 1 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: IA_PROVIDERS
        value: gemini,nvidia
      - key: AQ.Ab8RN6LL4otKHTTcDXDgxJndYZxcQKcap_wSZlfBabo6cgLuYg
        sync: false
      - key: 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
        sync: false
      - key: JARVIS_API_TOKEN
        generateValue: true
